language: node_js
node_js:
  - '6'
  - '5'
  - '4'
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g bower polymer-cli
  - bower install
script:
  - xvfb-run polymer test
